package StudentApp;


import java.util.Arrays;
import java.util.List;

/**
* StudentApp/_StudentManagementStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StudentManagement.idl
* lundi 8 juillet 2024 16 h 38 CEST
*/

public class _StudentManagementStub extends org.omg.CORBA.portable.ObjectImpl implements StudentApp.StudentManagement
{

  public List<Student> students ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("students", true);
                $in = _invoke ($out);
                StudentApp.Student $result[] = StudentApp.studentSeqHelper.read ($in);
                return Arrays.asList($result);
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return students (        );
            } finally {
                _releaseReply ($in);
            }
  } // students

  public List<Student> getStudentsByPromotion (String promotion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getStudentsByPromotion", true);
                $out.write_string (promotion);
                $in = _invoke ($out);
                StudentApp.Student $result[] = StudentApp.studentSeqHelper.read ($in);
                return Arrays.asList($result);
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getStudentsByPromotion (promotion        );
            } finally {
                _releaseReply ($in);
            }
  } // getStudentsByPromotion

  public void add (String matricule, String promotion, String naissance, String nom)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("add", true);
                $out.write_string (matricule);
                $out.write_string (promotion);
                $out.write_string (naissance);
                $out.write_string (nom);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                add (matricule, promotion, naissance, nom        );
            } finally {
                _releaseReply ($in);
            }
  } // add

  public void changePromotion (String matricule, String promotion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("changePromotion", true);
                $out.write_string (matricule);
                $out.write_string (promotion);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                changePromotion (matricule, promotion        );
            } finally {
                _releaseReply ($in);
            }
  } // changePromotion

  public void changeDate (String matricule, String date)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("changeDate", true);
                $out.write_string (matricule);
                $out.write_string (date);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                changeDate (matricule, date        );
            } finally {
                _releaseReply ($in);
            }
  } // changeDate

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StudentApp/StudentManagement:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "StudentApp._StudentManagementStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _StudentManagementStub
