package StudentApp;


/**
* StudentApp/Student.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StudentManagement.idl
* lundi 8 juillet 2024 16 h 38 CEST
*/

public final class Student implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String matricule = null;
  public String date = null;
  public String promotion = null;

  public Student ()
  {
  } // ctor

  public Student (String _name, String _matricule, String _date, String _promotion)
  {
    name = _name;
    matricule = _matricule;
    date = _date;
    promotion = _promotion;
  } // ctor

} // class Student
