package StudentApp;


/**
* StudentApp/studentSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StudentManagement.idl
* lundi 8 juillet 2024 16 h 38 CEST
*/

public final class studentSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public StudentApp.Student value[] = null;

  public studentSeqHolder ()
  {
  }

  public studentSeqHolder (StudentApp.Student[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudentApp.studentSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudentApp.studentSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudentApp.studentSeqHelper.type ();
  }

}
